### PR TITLE
load from https

### PR DESCRIPTION
**Pull request by Leooo**

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by okuryu** [comment]
It need to change all `yui.yahooapis.com` to `yui-s.yahooapis.com`.

**Comment by Leooo** [comment]
@okuryu correct, amended thanks

**Comment by Leooo** [comment]
@okuryu can we create new release 0.10.3 please?

**Comment by okuryu** [comment]
yup, I'm going to publish it this month.

**Pull request merged**
