### PR TITLE
Add Author-tag to default theme

### PR DESCRIPTION
**Pull request by MTRNord**
Show up Author Tag in Theme. It was implemented as Tag but not shown at the page.

### CODE REVIEW

**Comment by MTRNord** [comment]
Anyone who wants to check this? Or is the proect dead?

**Comment by okuryu** [comment]
Okay, I'll try to check asap.

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by MTRNord** [comment]
I wonder if this will ever get reviewed or even merged.. </ Bumping PR>

**Comment by MTRNord** [comment]
Closing as I am not expecting that this ever gets merged. Ping me if you want to revive it

**Pull request closed without merging**
