### PR TITLE
Bump markdown-it version to ^4.1.0

### PR DESCRIPTION
**Pull request by okuryu**

### CODE REVIEW

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by hhff** [comment]
Hi @okuryu - do you think this will fix some of the strange indenting things we've been seeing?

**Comment by okuryu** [comment]
@hhff Nope if you say about #323, but I'll take a look for #323 separately.

**Comment by hhff** [comment]
ok thankyou @okuryu !

**Pull request merged**
