### PR TITLE
Fixed typo error

### PR DESCRIPTION
**Pull request by jordilopez**
`extension_for` blocks are never showing up. This is because there's a typo
error on `lib/builder.js`.

`entension_for` is wrong, replaced with `extension_for` instead.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by yahoocla** [comment]
CLA is valid!

**Comment by stefanpenner** [comment]
could we get a regression test?

**Comment by zigotica** [comment]
@stefanpenner @yahoocla do you have any passing test for the original code which was clearly wrong? if you could please point me to that file we will provide a fix to the test as well. thank you

**Comment by jordilopez** [comment]
@stefanpenner ok, added test.

**Pull request merged**
